# Generated by Django 6.0.4 on 2026-05-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrant_type', models.CharField(choices=[('eleve', "L'élève lui-même"), ('parent', 'Un parent / tuteur')], default='eleve', max_length=10, verbose_name="Qui s'inscrit")),
                ('last_name', models.CharField(max_length=100, verbose_name="Nom de l'élève")),
                ('first_name', models.CharField(max_length=100, verbose_name="Prénom(s) de l'élève")),
                ('school', models.CharField(max_length=200, verbose_name='Établissement scolaire')),
                ('phone', models.CharField(max_length=20, verbose_name='Numéro de contact')),
                ('phone_owner', models.CharField(choices=[('eleve', "L'élève"), ('pere', 'Le père'), ('mere', 'La mère'), ('tuteur', 'Un tuteur')], default='eleve', max_length=10, verbose_name='Ce numéro appartient à')),
                ('level', models.CharField(choices=[('3eme', '3ème'), ('1ere', '1ères C & D'), ('tle', 'Terminales C & D')], max_length=10, verbose_name='Niveau')),
                ('serie', models.CharField(blank=True, choices=[('C', 'Série C'), ('D', 'Série D')], default='', max_length=1, verbose_name='Série')),
                ('parent_name', models.CharField(blank=True, max_length=200, verbose_name='Nom du parent / tuteur')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du parent')),
                ('status', models.CharField(choices=[('pending', 'En attente de paiement'), ('active', 'Inscrit — Paiement confirmé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
