# Generated by Django 6.0.4 on 2026-05-05 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0002_alter_student_level_alter_user_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente de paiement'), ('active', 'Active'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Formation')),
                ('student', models.ForeignKey(blank=True, limit_choices_to={'role': 'apprenant'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Apprenant (compte)')),
                ('student_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.student', verbose_name='Apprenant (enfant de parent)')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('student__isnull', False)), fields=('student', 'course'), name='unique_student_course'), models.UniqueConstraint(condition=models.Q(('student_child__isnull', False)), fields=('student_child', 'course'), name='unique_child_course')],
            },
        ),
    ]
