# Generated by Django 6.0.4 on 2026-05-09 13:19

import django.db.models.deletion
import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (FCFA)')),
                ('method', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('moov', 'MOOV Money')], max_length=10, verbose_name='Réseau utilisé')),
                ('phone_used', models.CharField(max_length=20, verbose_name='Numéro ayant effectué le paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente de confirmation'), ('confirmed', 'Confirmé'), ('failed', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut')),
                ('receipt_number', models.CharField(default=payments.models.generate_receipt_number, max_length=30, unique=True, verbose_name='Numéro de reçu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de déclaration')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='enrollments.enrollment', verbose_name='Inscription')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
    ]
