# Generated by Django 6.0.4 on 2026-05-06 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant (FCFA)')),
                ('method', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('moov', 'MOOV Money'), ('celtiis', 'Celtiis Money'), ('cash', 'Espèces sur place')], max_length=10, verbose_name='Méthode')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence transaction')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='enrollments.enrollment', verbose_name='Inscription')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
    ]
