# Generated by Django 6.0.4 on 2026-05-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('3eme', '3ème'), ('1ereC', '1ère C'), ('1ereD', '1ère D'), ('tleC', 'Terminale C'), ('tleD', 'Terminale D')], max_length=10, verbose_name='Classe / Niveau'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, choices=[('3eme', '3ème'), ('1ereC', '1ère C'), ('1ereD', '1ère D'), ('tleC', 'Terminale C'), ('tleD', 'Terminale D')], max_length=10, verbose_name='Classe / Niveau'),
        ),
    ]
