# Generated by Django 6.0.4 on 2026-05-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('level', models.CharField(choices=[('3eme', '3ème'), ('1ereC', '1ère C'), ('1ereD', '1ère D'), ('tleC', 'Terminale C'), ('tleD', 'Terminale D')], max_length=10, verbose_name='Classe')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('subjects', models.CharField(help_text='Ex : Maths, PCT, SVT, Anglais', max_length=300, verbose_name='Matières enseignées')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Tarif (FCFA)')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['level'],
            },
        ),
    ]
