# Generated by Django 6.0.4 on 2026-05-16 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('badge_text', models.CharField(blank=True, max_length=100)),
                ('short_description', models.TextField(max_length=500)),
                ('detailed_description', models.TextField(blank=True, help_text='Contenu complet du cours (HTML accepté)')),
                ('sub_subjects', models.JSONField(blank=True, default=list)),
                ('nb_sheets', models.PositiveSmallIntegerField(default=0)),
                ('nb_exercises', models.PositiveSmallIntegerField(default=0)),
                ('has_corrections', models.BooleanField(default=True)),
                ('has_audio', models.BooleanField(default=False)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='courses/pdfs/')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='courses/previews/')),
                ('preview_text', models.TextField(blank=True, help_text='Extrait pour aperçu popup')),
                ('is_downloadable', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='resources.level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='resources.subject')),
            ],
            options={
                'ordering': ['order', 'level__order', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('media_type', models.CharField(choices=[('text', 'Texte structuré'), ('image', 'Image'), ('video', 'Vidéo'), ('pdf', 'PDF')], default='text', max_length=10)),
                ('media_file', models.FileField(blank=True, help_text='Image, PDF ou vidéo (si fichier local)', null=True, upload_to='tips/media/')),
                ('video_url', models.URLField(blank=True, help_text='URL YouTube/Viméo (si vidéo hébergée)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='tips/thumbnails/')),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('detailed_content', models.TextField(blank=True, help_text="Description ou contenu textuel de l'astuce")),
                ('is_downloadable', models.BooleanField(default=False)),
                ('download_file', models.FileField(blank=True, null=True, upload_to='tips/downloads/')),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='resources.level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='resources.subject')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
